name: 🚀 Déploiement BRANCH → DEV

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: branch-deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy-branch-dev:
    name: 🚀 Déployer la branche ${{ github.ref_name }} vers DEV

    uses: LeZouzouEnWeb/workflows/.github/workflows/branch-deploy.yml@v1.0.10

    permissions:
      contents: write
      pull-requests: write

    secrets:
      REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    with:
      ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}
      ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}
      remote_env: dev
      enable_mirror: false
