name: 🚀 Déploiement PROD

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-prod:
    name: 🚀 Déploiement PROD
    if: github.event.pull_request.merged == true
    uses: LeZouzouEnWeb/workflows/.github/workflows/deploy.yml@v1.0.10
    permissions:
      contents: write
      pull-requests: write
    secrets:
      # Secrets requis pour le déploiement SSH
      REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}        # Chemin de base sur le serveur
      SFTP_HOST: ${{ secrets.SFTP_HOST }}                # Adresse du serveur
      SFTP_USER: ${{ secrets.SFTP_USER }}                # Utilisateur SSH
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}    # Clé privée SSH
    with:
      # Variables pour construire le chemin distant
      ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}         # Ex: www
      ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}           # Ex: mon-site
      remote_env: 'prod'
      enable_mirror: false
